name: validate-definition

on:
  push:
    branches: [ main ]
    
jobs:
  Validate-ASN1-Definition:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # checkout repo content
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install ASN.1 Tools
        run: pip3 install asn1tools
      - name: Validate data-item.asn through sample (1)
        run: |
         python3 -c "
         import asn1tools
         dataItem = asn1tools.compile_files('$GITHUB_WORKSPACE/descriptions/monopad-ada-1.0/data-item.asn')
         data = open('$GITHUB_WORKSPACE/descriptions/monopad-ada-1.0/data-item-sample-1.ber','rb').read()
         dataItem.decode('DataItem', data)"
      - name: Validate data-item.asn through sample (2)
        run: |
         python3 -c "
         import asn1tools
         dataItem = asn1tools.compile_files('$GITHUB_WORKSPACE/descriptions/monopad-ada-1.0/data-item.asn')
         data = open('$GITHUB_WORKSPACE/descriptions/monopad-ada-1.0/data-item-sample-2.ber','rb').read()
         dataItem.decode('DataItem', data)"
      - name: Validate data-item.asn through sample (empty)
        run: |
         python3 -c "
         import asn1tools
         dataItem = asn1tools.compile_files('$GITHUB_WORKSPACE/descriptions/monopad-ada-1.0/data-item.asn')
         data = open('$GITHUB_WORKSPACE/descriptions/monopad-ada-1.0/data-item-sample-empty.ber','rb').read()
         dataItem.decode('DataItem', data)"

